server:
  port: ${port:8761}

spring:
  application:
    name: discoveryserver

eureka:
  environment: default
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/

---
server:
  port: 8761

spring:
  profiles: des

eureka:
  instance:
    hostname: 127.0.0.1

---
server:
  port: 8762

spring:
  profiles: pre

eureka:
  instance:
    hostname: 127.0.0.1

---
server:
  port: 8763

spring:
  profiles: prod

eureka:
  instance:
    hostname: 127.0.0.1
