server:
  port: ${PORT:8883}
  
spring:
  profiles: des
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka,http://localhost:8763/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
---
server:
  port: ${8884}
  
spring:
  profiles: pre
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka,http://localhost:8763/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      hostname: 127.0.0.1
      zone: zone2
---
server:
  port: ${8885}
  
spring:
  profiles: prod
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/, http://localhost:8761/eureka,http://localhost:8762/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      hostname: 127.0.0.1
      zone: zone3
