
  
spring:
  profiles: zone1
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka,http://localhost:8763/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
server:
  port: ${PORT:8883}
---

  
spring:
  profiles: zone2
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka,http://localhost:8763/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
server:
  port: ${PORT:8884}
---

  
spring:
  profiles: zone3
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8761/eureka,http://localhost:8762/eureka
      registerWithEureka: false
      preferSameZoneEureka: true
server:
  port: ${PORT:8885}
