spring:
  profiles : zone1
application:
  name: eureka-server-des
server:
  port:  ${port:8761}
  
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      instance:
          hostname: localhost
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
   server:
      renewalPercentThreshold: 0.8
      enableSelfRreservation: true
      
---

spring:
  profiles: zone2
  application:
    name: eureka-server-pre
server:
  port:  ${port:8762}
eureka:
  client:
      registerWithEureka: false
      fetchRegistry: false
      instance:
          hostname: localhost
      serviceUrl:
        defaultZone: http://localhost:8762/eureka/
  server:
      renewalPercentThreshold: 0.8
      enableSelfRreservation: true    
  
