server:
  port: ${port:8761}

spring:
  application:
    name: discoveryserver

eureka:
  environment: default
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.132:8761/eureka/,http://192.168.1.133:8762/eureka/,http://192.168.1.134:8763/eureka/

---
server:
  port: 8761

spring:
  profiles: des

eureka:
  instance:
    hostname: 192.168.1.132

---
server:
  port: 8762

spring:
  profiles: pre

eureka:
  instance:
    hostname: 192.168.1.133

---
server:
  port: 8763

spring:
  profiles: prod

eureka:
  instance:
    hostname: 192.168.1.134
