server:
  port: ${8883}
  
spring:
  profiles: des
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: des
---
server:
  port: ${8884}
  
spring:
  profiles: pre
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8764/eureka/
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      hostname: 127.0.0.1
      zone: pre
---
server:
  port: ${8885}
  
spring:
  profiles: prod
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
      registerWithEureka: false
      preferSameZoneEureka: true
  instance:
    metadataMap:
      hostname: 127.0.0.1
      zone: prod
