spring:
  profiles : zone1
application:
  name: eureka-server
server:
  port: 8760
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      instance:
          hostname: localhost
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
   server:
      renewalPercentThreshold: 0.8
      enableSelfRreservation: true
      
---

spring:
  profiles: zone2
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
      registerWithEureka: false
      fetchRegistry: false
      instance:
          hostname: localhost
      serviceUrl:
        defaultZone: http://localhost:8760/eureka/
  server:
      renewalPercentThreshold: 0.8
      enableSelfRreservation: true    
