spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ADM-SoftDev/RepositoryMs.git

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
  instance:
    hostname: localhost
  availability-zones:
      region-1: zone1,zone2
     
spring.profiles.active: zone1
